// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_SVRmsjPDNxs7q_pYj0QNFXIrqnqkSDE',
    appId: '1:1022761324834:web:d966d33a386efb9192157b',
    messagingSenderId: '1022761324834',
    projectId: 'aiview-fa69f',
    authDomain: 'aiview-fa69f.firebaseapp.com',
    storageBucket: 'aiview-fa69f.firebasestorage.app',
    measurementId: 'G-R4BK02VM8F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhG43CePUtngWPlpyAsnfTyGwjOgNfZLE',
    appId: '1:1022761324834:ios:543db0f6f486184292157b',
    messagingSenderId: '1022761324834',
    projectId: 'aiview-fa69f',
    storageBucket: 'aiview-fa69f.firebasestorage.app',
    iosClientId: '1022761324834-vv9160hvv1uvhhchggebkdqbe5347soa.apps.googleusercontent.com',
    iosBundleId: 'com.jmy.intelliview',
  );
}
