name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10","3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional: dev/test extras
          pip install pytest pytest-asyncio

      - name: Run all tests
        run: |
          cd backend
          export CI=true
          echo '{
            "type": "service_account",
            "project_id": "dummy",
            "private_key_id": "dummy",
            "private_key": "-----BEGIN PRIVATE KEY-----\nFAKE\n-----END PRIVATE KEY-----\n",
            "client_email": "dummy@dummy.iam.gserviceaccount.com",
            "client_id": "1234567890"
          }' > dummy.json
          export GOOGLE_CLOUD_PROJECT=dummy
          export FIREBASE_KEY_PATH=$(pwd)/dummy.json
          export GOOGLE_CLOUD_LOCATION=us-central1
          export GOOGLE_GENAI_USE_VERTEXAI=TRUE
          pytest --maxfail=5 --disable-warnings -q
